name: exchange
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  permission_handler: ^10.2.0
  device_info_plus: ^8.2.0
  camera: ^0.9.4+5
  auto_size_text: ^3.0.0
  g_recaptcha_v3: ^0.0.5
  carousel_pro: ^1.0.0
  flutter_sparkline: ^0.1.0
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0
  rxdart: ^0.27.5
  get_ip_address: ^0.0.5
  bmnav: ^0.3.4
  carousel_slider: ^4.1.1
  image_picker: 0.8.5+3
  custom_switch: ^0.0.1
  percent_indicator: 4.0.1
  shared_preferences: ^2.0.7
  toast: ^0.3.0
  http: ^0.13.6
  socket_io_client: ^2.0.1
  web_socket_channel:
  websocket: 0.0.5
  fluttertoast: ^8.0.9
  flutter_spinkit:
  page_transition: ^2.0.2
  bottom_bar:
  #  flutter_html:
  intl:
  path:
  slider_button: ^2.0.0
  flutter_svg: ^1.0.3
  #  webview_flutter:
  wakelock: ^0.6.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_barcode_scanner: ^2.0.0
  flutter_rating_bar: ^4.0.0
  circular_bottom_navigation: ^2.0.0
  custom_radio_group_list: ^1.0.0
  dotted_border:
  im_stepper: ^0.1.3
  badges:
  provider:
  toggle_switch: ^2.0.1
  photo_view: ^0.14.0
  lottie: ^1.2.1
  flutter_staggered_animations: ^1.0.0
  pull_to_refresh: ^2.0.0
  flutter_animator: ^3.2.1
  dropdown_search: ^3.0.1
  searchable_dropdown: ^1.1.3
  marquee_widget: ^1.2.0
  #  k_chart: 0.6.0
  k_chart: ^0.6.1
  animated_text_kit: 4.2.1
  #  slider_captcha: 0.0.7
  webview_flutter_plus: ^0.3.0+2
  floating_bottom_navigation_bar: 1.5.2
  internet_connection_checker: 0.0.1+3
  day_night_switcher: ^0.2.0+1
  #  connectivity_plus: ^2.2.0
  qr_flutter: ^4.0.0
  flutter_html:
  email_validator:
  image_cropper: 1.5.1
  # connectivity_plus: ^2.3.0
  just_the_tooltip: ^0.0.11+2
  awesome_notifications: ^0.7.4+1

  flutter_background_service: 1.0.4
  sqflite: ^2.0.2+1
  candlesticks: ^2.1.0
  url_launcher: ^6.1.5
  in_app_update: ^3.0.0
  expandable: ^5.0.1
  buttons_tabbar: ^1.3.6
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logoApps.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: gainers
      fonts:
        - asset: assets/icon/ic_gainers.ttf
    - family: message
      fonts:
        - asset: assets/icon/ic_message.ttf
    - family: tab
      fonts:
        - asset: assets/icon/ic_tab.ttf
    - family: wallet
      fonts:
        - asset: assets/icon/ic_wallet.ttf
    - family: tab1
      fonts:
        - asset: assets/icon/ic_tab1.ttf
    - family: tab2
      fonts:
        - asset: assets/icon/ic_tab2.ttf
    - family: tab3
      fonts:
        - asset: assets/icon/ic_tab3.ttf
    - family: tab4
      fonts:
        - asset: assets/icon/ic_tab4.ttf
    - family: tab5
      fonts:
        - asset: assets/icon/ic_tab5.ttf
    - family: loser
      fonts:
        - asset: assets/icon/ic_loser.ttf
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family: IBM Plex Sans
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
    - family: Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family: Lemon
      fonts:
        - asset: assets/font/Lemon-Regular.ttf
          weight: 400
    - family: IBM Plex Sans
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight: 600
    - family: Pragmatica
      fonts:
        - asset: assets/font/pragmatica_bold.ttf
          weight: 500

  assets:
    - assets/
    - assets/image/ 
    - assets/image/icon/
    - assets/image/logo2.png
    - assets/webpages/index.html
    - assets/ilustration/boarding1.png
    - assets/ilustration/noData.png
    - assets/ilustration/splash.png
    - assets/ilustration/boarding2.png
    - assets/ilustration/boarding3.png
    - assets/image/banner/banner1.png
    - assets/image/banner/banner2.png
    - assets/image/banner/banner3.jpg
    - assets/image/banner/banner4.png
    - assets/image/kyc.png
    - assets/image/2FA.png
    - assets/image/daybackground.png
    - assets/image/plainwhite.png
    - assets/image/upload.png
    - assets/image/refer.png
    - assets/image/credit-card.png
    - assets/image/trade.png
    - assets/image/24chng.png
    - assets/image/hot.png
    - assets/image/splash_screen.png
    - assets/image/loginHeader.png
    - assets/image/usdt.png
    - assets/image/logout.png
    - assets/image/change password.png
    - assets/image/signupHeader.png
    - assets/image/gainers.png
    - assets/image/losers.png
    - assets/image/market/ae.png
    - assets/image/log.png
    - assets/image/report.png
    - assets/image/market/aion.png
    - assets/image/market/bat.png
    - assets/image/market/BCH.png
    - assets/image/market/bee.png
    - assets/image/market/bnt.png
    - assets/image/market/btc.png
    - assets/image/market/dnt.png
    - assets/image/market/elf.png
    - assets/image/market/EOS.png
    - assets/image/market/ETC.png
    - assets/image/market/eth.png
    - assets/image/market/NEO.png
    - assets/image/market/RIPLE.png
    - assets/image/btt.png
    - assets/image/market/bitcoin.png
    - assets/image/article1.jpg
    - assets/image/create_wallet.png
    - assets/image/News_Image/Asia.jpg
    - assets/image/News_Image/BlockStream.jpg
    - assets/image/News_Image/BNB.jpg
    - assets/image/News_Image/CBOE.jpg
    - assets/image/News_Image/CryptoBroker.jpg
    - assets/image/News_Image/EOSget.jpg
    - assets/image/News_Image/MarketSentiment.jpg
    - assets/image/News_Image/Mt.Gox.jpg
    - assets/image/News_Image/NewCripto.jpg
    - assets/image/News_Image/Twitter.jpg
    - assets/image/News_Image/YouCan.jpg
    - assets/image/News_Image/Ziliqa.jpg
    - assets/image/setting/lightMode.png
    - assets/image/setting/nightMode.png
    - assets/image/qrCode.png
    - assets/image/transaction.png
    - assets/image/P2P.png
    - assets/image/messageAppbar.png
    - assets/image/T1_noMessage.png
    - assets/image/icon/icon_file.png
    - assets/image/icon/icon_image.png
    - assets/image/icon/icon_microphone.png
    - assets/image/icon/icon_monitor.png
    - assets/image/icon/icon_video.png
    - assets/image/recaptcha.png
    - assets/avatars/avatar-1.jpg
    - assets/avatars/avatar-2.jpg
    - assets/avatars/avatar-3.jpg
    - assets/avatars/avatar-4.jpg
    - assets/avatars/avatar-5.jpg
    - assets/avatars/avatar-6.jpg
    - assets/avatars/cryptocurrency.jpeg
    - assets/avatars/avatar-7-line.png
    - assets/avatars/default-avatar.jpg
    - assets/image/crypto_icon/icon_bitcoin.png
    - assets/image/crypto_icon/icon_bee.png
    - assets/image/crypto_icon/icon_elf.png
    - assets/image/crypto_icon/icon_eth.png
    - assets/image/crypto_icon/icon_lnc.png
    - assets/image/Template_2_image/tabBar.png
    - assets/image/Template_3/people.png
    - assets/image/Template_3/scan.png
    - assets/image/Template_3/transfer.png
    - assets/image/Template_3/menu_bus.png
    - assets/image/Template_3/menu_home.png
    - assets/image/Template_3/menu_shopping.png
    - assets/image/Template_3/menu_tv.png
    - assets/image/Template_3/slackLogo.png
    - assets/image/Template_3/solariaLogo.jpg
    - assets/image/Template_3/twitchLogo.png
    - assets/image/Template_3/finance_layout/bils_finance.png
    - assets/image/Template_3/finance_layout/doctor_finance.png
    - assets/image/Template_3/finance_layout/hangout_finance.png
    - assets/image/Template_3/finance_layout/lifeStyle_finance.png
    - assets/image/Template_3/finance_layout/workout_finance.png
    - assets/image/Template_3/deals_layout/buildingMenu.png
    - assets/image/Template_3/deals_layout/cardMenu.png
    - assets/image/Template_3/deals_layout/financeMenu.png
    - assets/image/Template_3/deals_layout/findMenu.png
    - assets/image/Template_3/deals_layout/giveMenu.png
    - assets/image/Template_3/deals_layout/growthMenu.png
    - assets/image/Template_3/deals_layout/locationMenu.png
    - assets/image/Template_3/deals_layout/moneyMenu.png
    - assets/image/Template_3/deals_layout/saveMenu.png
    - assets/image/Template_3/deals_layout/shareMenu.png
    - assets/image/Template_3/historyEmpty.png
    - assets/icon/Template4/aboutapp.png
    - assets/icon/Template4/callcenter.png
    - assets/icon/Template4/chat.png
    - assets/icon/Template4/creditAcount.png
    - assets/icon/Template4/notification.png
    - assets/icon/Template4/setting.png
    - assets/icon/Template4/truck.png
    - assets/image/Template_4/notifications.png
    - assets/image/Template_4/creditCardVisa.png
    - assets/image/Template_4/credit.png
    - assets/image/Template_4/contact_us.png
    - assets/image/Template_4/noMessage.png
    - assets/image/Template_5/noTransaction.png
    - assets/image/Template_5/alarm.png
    - assets/image/Template_5/creditCard.png
    - assets/image/logoApps.png
    - assets/image/logoApps1.png
    - assets/image/background.png
    - assets/image/icon/facebook.png
    - assets/image/icon/twitter.png
    - assets/image/icon/insta.png
    - assets/image/icon/telegram.png
    - assets/image/staking.png
    - assets/image/reward.png
    - assets/image/airdrop.png
#    - assets/image/icon/instagram.png
#    - assets/image/icon/telegram.png
#    - assets/image/icon/twitter.png

# To add assets to your application, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.io/assets-and-images/#resolution-aware.

# For details regarding adding assets from package dependencies, see
# https://flutter.io/assets-and-images/#from-packages

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.io/custom-fonts/#from-packages
